FROM wordpress:php8.3-fpm

# Developer tools
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    procps \
    vim \
    nano \
    less \
    unzip \
    zip \
    git \
    htop \
    mariadb-client \
    && rm -rf /var/lib/apt/lists/*

COPY php-custom.ini /usr/local/etc/php/conf.d/custom.ini
COPY php-fpm.conf /usr/local/etc/php-fpm.d/zz-custom.conf
